language: ruby
bundler_args: --without debug
before_script:
  - ulimit -c unlimited -S
  - "gem update --system"
before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-server-dev-9.4
script: "bundle exec rspec spec"
env:
  - CI=true
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby
cache: bundler
sudo: true
matrix:
  allow_failures:
    - rvm: jruby
dist: trusty
