language: ruby
bundler_args: --without debug
before_script:
  - ulimit -c unlimited -S
script: "bundle exec rspec spec"
env:
  - CI=true
rvm:
  - 2.2
  - 2.3
  - 2.4
  - rbx-3
before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-server-dev-9.4
cache: bundler
sudo: true
matrix:
  allow_failures:
    - rvm: rbx-3
dist: trusty
