language: ruby
bundler_args: --without debug
before_script:
  - ulimit -c unlimited -S
script: "bundle exec rspec spec"
env:
  - CI=true
rvm:
  - 2.2.5
  - 2.3.1
  - rbx
before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-server-dev-9.4
cache: bundler
sudo: true
matrix:
  allow_failures:
    - rvm: rbx
